### ISSUE TITLE
Contact form 7 (WP) submitting twice

### ISSUE THREAD

**Issue by alonazisser** [swup/forms-plugin#27]
Hi,
I have an issue. would appreciate your help:
Made a custom function on the submitForm event.
It works perfectly after the content is loaded with Swup, but if I reload the page (F5) and submit the form again, it is submitting twice.
I am using the CF7 plugin on WordPress, Does  SwupFormsPlugin suppose to prevent the default form action and do it separately? 
trying to figure out a workaround for that...

**Adding my code:**

```
const options = {
  containers: ["#page"],
  animateHistoryBrowsing: false,
  cache: false,
	plugins: [
	    new SwupScrollPlugin({
	        animateScroll: false,
	        doScrollingRightAway: true,
	    }),
	    new SwupFormsPlugin({ formSelector: 'form.wpcf7-form' }),
	]  
};

const swup = new Swup(options);

init();

swup.on('contentReplaced', init);
swup.on('submitForm', formSubmit);
```

**The custom function sending the serialized form to a third party api:** 

```
function formSubmit(event) {

        jQuery('html').addClass('is-formsubmitting');
        inputs = jQuery(event.delegateTarget).serialize();

        jQuery.ajax({
            type: 'POST',
            url: ajax_custom.ajaxurl,
            data: {
                action: "send_data_to_iplan",
                inputs: inputs
            },
            success: function (data) {
                console.log(data);
                if(!data.includes("ok") || data.indexOf("ok") <= 0){
                    $message = 'error ha accrued;
                    console.log('this is the reason the message failed:' , data);
                }
            }
        });

}

```

Thank you!

**Comment by daun** [comment]
The form plugin will perform the submission for you -- there should be no need to send the ajax request yourself.

**Comment by daun** [comment]
If you do need to send both requests (form as well as ajax) at the same time, it should still work as in your example. You'll need to make sure the WordPress form plugin doesn't execute its JS as well.

**Comment by alonazisser** [comment]
Thank you @daun !
I managed to disable the cf7 submission by adding: 

```
document.addEventListener( 'wpcf7submit', function( event ) {
	return false;
}, false );
```

Now the form is submitted once by swup.js forms plugin. :)

**Comment by daun** [comment]
Perfect!
