### ISSUE TITLE
Improve detection of form submission into new tab

### ISSUE THREAD

**Issue by hirasso** [swup/forms-plugin#29]
[As decribed here](https://github.com/swup/forms-plugin/pull/26#discussion_r958422825), we need to find a way to detect if a form submission was sent to a new tab. 

This behavior is natively supported by Chrome and Safari on MAC by holding down the `Meta` (command) key and by Edge on Windows by holding the `Control` (ctrl) key. There exists an [extension for FireFox](https://github.com/mikeconley/tab-submit-basic) that makes the same thing possible.

My first idea would be to use [`document.visibiltyState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState). Opening a new tab should hide the current tab, right? I will test this out.

**Comment by hirasso** [comment]
Note: The FireFox extension catches the form submit event before it reaches Swup, so the form is actually being submitted to a new tab. Because of this, the `openFormSubmitInNewTab` is also not being fired.

**Comment by daun** [comment]
Current state of affairs:

- Chrome/Safari will open a new tab when cmd-clicking the submit button
- Firefox will NOT open a new tab (see [BugZilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=17754))
- Cannot test behavior on Windows or Edge
- SubmitEvent does not have `metaKey` or similar attributes to check against
- Google does NOT respect the cmd key when submitting searches
- GitHub respects cmd key, even when submitting via Enter key from an input

**Comment by hirasso** [comment]
I updated [the test site](https://test.rassohilber.com/swup-forms-plugin/test/) with my proposed fix. The event `openFormSubmitInNewTab` should be fired in chrome and safari (watch the console)

**Comment by daun** [comment]
Some more pointers for further research/inspiration: Turbo's form handling.

- [form_link_click_observer.ts](https://github.com/hotwired/turbo/blob/main/src/observers/form_link_click_observer.ts)
- [form_submit_observer.ts](https://github.com/hotwired/turbo/blob/main/src/observers/form_submit_observer.ts)
- [form_submission.ts](https://github.com/hotwired/turbo/blob/main/src/core/drive/form_submission.ts)
- [submit-event.ts](https://github.com/hotwired/turbo/blob/main/src/polyfills/submit-event.ts)

**Comment by hirasso** [comment]
Just tested it with Edge on Windows, works as well. With the `control` key in that case.
