### ISSUE TITLE
plugin may not take note of any custom transition attribute?

### ISSUE THREAD

**Issue by kezabelle** [swup/forms-plugin#4]
Apologies if this is incorrect and wasting your time, I'm only beginning to get to grips with both swup *and* this plugin!

Before `loadPage` occurs in swup, it looks for `event.delegateTarget.getAttribute('data-swup-transition')` to add to the given `loadPage({options...})`, which will thus either contain the given transition or `null` (with `null` being the *unset* state)

Decorating the target form using this plugin (marking it up as `<form [...] data-swup-form data-swup-transition="search-form">` for example) however doesn't do the same thing -- the possibility of a `data-swup-transition` seems absent from the `onFormSubmit` definition. In my case, being a *search* form, it's a GET, but I think the problem could apply to POST too.

Ignoring that, this plugin *Just Works*, which is super nice, thanks for providing it!

**Comment by gmrchk** [comment]
Hi, it took a while, but v1.1.0 I just released shouldn't have this problem anymore. Please let me know if there are any other issues. 

Thank you for reporting. 🙏
