### ISSUE TITLE
[Feature Request]: Remove empty values for GET requests

### ISSUE THREAD

**Issue by hirasso** [swup/forms-plugin#66]
### Describe the problem 🧐

I have a filter form that sometimes has empty values. This results in URLs with unnesecary empty parameters empty like for example this one:

```
?filter=&sort=date-asc
```
The `filter` parameter is not in use and I'd like to strip it off the URL. A quick search yields these results:

Use Case description: https://erik.joling.me/2021/02/17/remove-empty-input-values-from-url-when-submitting-an-html-form/

### Describe the propsed solution 😎

Since forms plugin already submits the form via `formData`, maybe we could introducing stripping empty values as a feature?

Possible Solution (untested): 

```diff
appendQueryParams(url: string, data: FormData): string {
	const path = url.split('?')[0];
+	for (const [name, value] of Array.from(data.entries())) {
+		if (typeof value === 'string' && value.trim() === '') data.delete(name);
+	}
	const query = new URLSearchParams(data as unknown as Record<string, string>).toString();
	return query ? `${path}?${query}` : path;
}
```

Source: https://stackoverflow.com/a/64029534/586823

### Alternatives considered 🤔

Implement the functionality myself, without the use of forms-plugin. 

This could break existing implementations, if the consumers server-side script doesn't verify if a query parameter exists, for example this would break: 

```php
$filter = $_GET['filter'];
```

This would still work:
```php
$filter = $_GET['filter'] ?? null;
```

To be completely save, we could hide the feature behind a flag `stripEmptyParams` or the like. Naming suggestions?

### How important is this feature to you? 🧭

Nice to have

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
I see no harm in implementing this, but we should definitely make this opt-in behind a feature flag. It's in theory diverging from browser behavior and there's a few gotchas with manipulating query params, but those are definitely not an issue on most sites, so let's do it :)

I've never heard of the `formdata` event before. Is it really as easy as doing this on all your forms? Would this already work with the forms plugin? If yes, there's probably not much to do here, as that's nice and portable.

```js
form.addEventListener('formdata', ({ formData }) => {
  for (let [name, value] of Array.from(formData.entries())) {
    if (!value) formData.delete(name)
  }
})
```

**Comment by hirasso** [comment]
Ah right! I overlooked the `formdata` event in the example. I think I'd still prefer to not use it, as in POST requests, stripping empty parameters wouldn't bring any advantages. I'll get to it
